sources:
  warehouse_pg:
    adapter: sql
    dsn: env:AG_SQL_DSN
  salesforce_main:
    adapter: soql
    instance_url: env:AG_SF_INSTANCE_URL
    auth: env:AG_SF_ACCESS_TOKEN
  payroll_csv:
    adapter: csv
    file_path: env:AG_PAYROLL_CSV_PATH
  mongo_main:
    adapter: mongodb
    dsn: env:AG_MONGODB_DSN
    database: env:AG_MONGODB_DATABASE
